export enum FrecuenciaSociedad {
  SEMANAL = 'SEMANAL',
  QUINCENAL = 'QUINCENAL',
  MENSUAL = 'MENSUAL',
}

export enum ModalidadTurno {
  MANUAL = 'MANUAL',
  ALEATORIA = 'ALEATORIA',
}

export enum TipoPago {
  EFECTIVO = 'EFECTIVO',
  DEPOSITO_BANCARIO = 'DEPOSITO_BANCARIO',
  TRANSFERENCIA = 'TRANSFERENCIA',
  MIXTO = 'MIXTO',
}

export enum EstadoSociedad {
  CONFIGURACION = 'CONFIGURACION',
  ACTIVA = 'ACTIVA',
  FINALIZADA = 'FINALIZADA',
  CANCELADA = 'CANCELADA',
}

export enum EstadoParticipante {
  INVITADO = 'INVITADO',
  ACTIVO = 'ACTIVO',
  RETIRADO = 'RETIRADO',
  EXPULSADO = 'EXPULSADO',
}

export enum EstadoInvitacion {
  PENDIENTE = 'PENDIENTE',
  ACEPTADA = 'ACEPTADA',
  RECHAZADA = 'RECHAZADA',
  EXPIRADA = 'EXPIRADA',
}

export enum EstadoCiclo {
  CONFIGURACION = 'CONFIGURACION',
  ACTIVO = 'ACTIVO',
  COMPLETADO = 'COMPLETADO',
  CANCELADO = 'CANCELADO',
}

export enum EstadoTurno {
  PENDIENTE = 'PENDIENTE',
  PAGADO = 'PAGADO',
  REPROGRAMADO = 'REPROGRAMADO',
}

export enum EstadoPago {
  PENDIENTE = 'PENDIENTE',
  REPORTADO = 'REPORTADO',
  CONFIRMADO = 'CONFIRMADO',
  RECHAZADO = 'RECHAZADO',
  ATRASADO = 'ATRASADO',
  INCUMPLIDO = 'INCUMPLIDO',
}

export enum TipoNotificacion {
  RECORDATORIO_PAGO = 'RECORDATORIO_PAGO',
  PAGO_CONFIRMADO = 'PAGO_CONFIRMADO',
  PAGO_RECHAZADO = 'PAGO_RECHAZADO',
  INVITACION_RECIBIDA = 'INVITACION_RECIBIDA',
  INVITACION_ACEPTADA = 'INVITACION_ACEPTADA',
  NUEVO_CICLO = 'NUEVO_CICLO',
  PROXIMO_COBRO = 'PROXIMO_COBRO',
  PROXIMO_VENCIMIENTO = 'PROXIMO_VENCIMIENTO',
  PARTICIPANTE_EXPULSADO = 'PARTICIPANTE_EXPULSADO',
}

export enum RolSociedad {
  ORGANIZADOR = 'ORGANIZADOR',
  PARTICIPANTE = 'PARTICIPANTE',
}
